name: Release

on:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false
          fetch-depth: 0
          ref: 'main'
      - name: Setup PNPM
        uses: pnpm/action-setup@v2.2.2
        with:
            version: "latest"
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
            node-version: "18"
            registry-url: "https://registry.npmjs.org"
            cache: "pnpm"
      - name: setup pnpm config
        run: pnpm config set store-dir $PNPM_CACHE_FOLDER
      - name: Install dependencies
        run: pnpm install
      - name: Build package
        run: pnpm build
      - name: who am i
        env:
            NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: pnpm whoami
      - name: create and publish versions
        uses: changesets/action@v1
        with:
          version: pnpm bump
          commit: "chore: update versions"
          title: "chore: update versions"
          publish: pnpm ci:publish
        env:
          GITHUB_TOKEN: ${{ secrets.WORK_FLOW_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}